name: CI

permissions: {}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential meson ninja-build gcovr clang-tidy clang-format
        
        git clone https://github.com/axboe/liburing.git
        cd liburing
        ./configure
        make
        sudo make install
        cd ..

    - name: Configure
      run: |
        chmod +x ./configure
        ./configure

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Generate code coverage
      run: |
        make coverage
      
    - name: Upload coverage XML report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-xml
        path: build/meson-logs/coverage.xml
        retention-days: 14
        
    - name: Upload SonarQube report
      uses: actions/upload-artifact@v4
      with:
        name: sonarqube-report
        path: build/meson-logs/sonarqube.xml
        retention-days: 14
        
    - name: Upload text coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-text
        path: build/meson-logs/coverage.txt
        retention-days: 14
        
    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: build/meson-logs/coveragereport/
        retention-days: 14

  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy clang-format

    - name: Check code formatting
      run: |
        git ls-tree -r HEAD --name-only | grep -E "cpp|hpp" | xargs -I {} clang-format --dry-run --Werror {}
        
    - name: Run clang-tidy analysis
      run: |
        mkdir -p build
        meson setup build || true
        mkdir -p analysis-reports
        git ls-tree -r HEAD --name-only | grep -E "cpp|hpp" | xargs -I {} sh -c 'clang-tidy {} -p ./build > analysis-reports/$(basename {}).txt 2>&1 || true'
      
    - name: Upload static analysis reports
      uses: actions/upload-artifact@v4
      with:
        name: static-analysis
        path: analysis-reports/
        retention-days: 14
